

x1 = float(input("Enter x1: "))
y1 = float(input("Enter y1: "))
x2 = float(input("Enter x2: "))
y2 = float(input("Enter y2: "))

# Calculate dx,dy
dx = x2 - x1
dy = y2 - y1

# Calculate steps
steps = abs(dx) if abs(dx) > abs(dy) else abs(dy)

# Calculate increment values
x_inc = dx / steps
y_inc = dy / steps

# Initialize starting point
x = x1
y = y1

print("\nPoints generated by DDA Line Drawing Algorithm:")


for i in range(int(steps) + 1):
    print(f"({round(x)}, {round(y)})")  
    x += x_inc
    y += y_inc
