# Bresenham Line Drawing Algorithm

x1 = int(input("Enter x1: "))
y1 = int(input("Enter y1: "))
x2 = int(input("Enter x2: "))
y2 = int(input("Enter y2: "))

# Calculate dx, dy
dx = abs(x2 - x1)
dy = abs(y2 - y1)

# Determine the direction of increment
sx = 1 if x2 > x1 else -1
sy = 1 if y2 > y1 else -1

# Initialize error term
err = dx - dy

print("\nPoints generated by Bresenham Line Drawing Algorithm:")

x, y = x1, y1
while True:
    print(f"({x}, {y})") 
    
    
    if x == x2 and y == y2:
        break

    e2 = 2 * err

    if e2 > -dy:
        err -= dy
        x += sx
    if e2 < dx:
        err += dx
        y += sy
